# Generated by Django 4.1.5 on 2023-03-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='speed',
        ),
    ]
