# Generated by Django 4.1.5 on 2023-03-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_test', '0002_remove_car_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='speed',
            field=models.IntegerField(default=1),
        ),
    ]
