# Generated by Django 4.1.5 on 2023-03-07 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_test', '0003_car_speed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
