# Generated by Django 4.1.5 on 2023-04-28 19:16

from django.db import migrations, models
import djongo.models.fields
import verification.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChessUser",
            fields=[
                ("is_activate", models.BooleanField(null=True)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=500, null=True)),
                ("password", models.CharField(max_length=500, null=True)),
                ("email", models.CharField(max_length=150, null=True)),
                (
                    "tokens",
                    djongo.models.fields.ArrayField(
                        model_container=verification.models.Token, null=True
                    ),
                ),
            ],
            options={
                "db_table": "chess_user",
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("expiration", models.DateField(null=True)),
                ("tokenHash", models.CharField(max_length=750)),
            ],
        ),
    ]
